### ISSUE TITLE
Something appears to be setting SIMP_RPM_dist ouside of the rpm_docker test

### ISSUE THREAD

**Issue by trevor-vaughan** [simp/simp-core#785]
The `SIMP_RPM_dist` environment variable is getting set outside of the `rpm_docker` acceptance test.

This means that building an EL7 build on an EL8 system ends up with `el8` in the dist tag.

This was not an issue until we started adding the dist tag to all RPMs.

Spawning a container and running everything by hand works properly so it's pollution from outside the job.

**Comment by trevor-vaughan** [comment]
It looks like this might be due to the constants being set by `simp-rake-helpers`. Going to try ignoring that one in the prep for the test to see if it works around it successfully.

**Comment by op-ct** [comment]
> It looks like this might be due to the constants being set by `simp-rake-helpers`.

Do we know what's polluting the job from outside, or how?

The relevant constants look like they're set at https://github.com/simp/rubygem-simp-rake-helpers/blob/master/lib/simp/rake/build/constants.rb#L26-L30, but only when `SIMP_RPM_dist` is empty (which itself is a workaround to the `RPM.system_dist` workaround that assumes the RPM is the same OS as the system the task is running from).
