### ISSUE TITLE
simp-core acceptance tests against Unstable repositories

### ISSUE THREAD

**Issue by trevor-vaughan** [simp/simp-core#791]
The latest RPMs have been uploaded to the [Unstable SIMP repository](https://download.simp-project.com/simp/yum/unstable/simp6/el/) and need to be validated against the acceptance tests.

**Comment by trevor-vaughan** [comment]
Working on EL7 testing using the `Vagrantfile` in `simp-core`. It's pretty much the fastest way to manually test.

**Comment by trevor-vaughan** [comment]
To easily test this via the `Vagrantfile`:

```diff
diff --git a/Vagrantfile b/Vagrantfile
index 14aa8fed..5eb6d9ea 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -40,6 +40,9 @@ Vagrant.configure('2') do |c|
     v.vm.provision 'shell',
       inline: 'yum install -y https://download.simp-project.com/simp-release-community.rpm'
+   v.vm.provision 'shell',
+      inline: 'echo unstable > /etc/yum/vars/simpreleasetype'
+
     # Install the puppet server
     v.vm.provision 'shell',
       inline: 'yum install -y puppetserver'
```

**Comment by trevor-vaughan** [comment]
Unable to test EL8 until simp/simp-core#795 is complete.

**Comment by trevor-vaughan** [comment]
@brandonrdn and @op-ct the `simp-adapter` RPM currently in the `unstable` repo does not have the necessary dependencies for `git` or `rsync` so the installation is failing.

**Comment by AndyAdrian-OP** [comment]
closing, 6.6.0 released
