### ISSUE TITLE
Updates to stdlib, concat, and chrony caused dependency issues

### ISSUE THREAD

**Issue by trevor-vaughan** [simp/simp-core#829]
## Issue

The following dependency issues are now present:

```
package: pupmod-camptocamp-systemd-2.12.0-1.el8.noarch from base
  unresolved deps:
    pupmod-puppetlabs-stdlib < 7.0.0
package: pupmod-puppet-firewalld-4.4.0-1.el8.noarch from base
  unresolved deps:
    pupmod-puppetlabs-stdlib < 7.0.0
package: pupmod-puppet-kmod-3.0.0-1.el8.noarch from base
  unresolved deps:
    pupmod-puppetlabs-stdlib < 7.0.0
package: pupmod-puppet-snmp-5.1.1-1.el8.noarch from base
  unresolved deps:
    pupmod-puppetlabs-stdlib < 7.0.0
package: pupmod-puppet-yum-4.3.0-1.el8.noarch from base
  unresolved deps:
    pupmod-puppetlabs-stdlib < 7.0.0
    pupmod-puppetlabs-concat < 7.0.0
package: pupmod-puppetlabs-puppet_authorization-0.5.1-1.el8.noarch from base
  unresolved deps:
    pupmod-puppetlabs-stdlib < 7.0.0
    pupmod-puppetlabs-concat < 7.0.0
package: pupmod-puppetlabs-puppetdb-7.5.0-1.el8.noarch from base
  unresolved deps:
    pupmod-puppetlabs-stdlib < 7.0.0
    pupmod-puppetlabs-postgresql < 7.0.0
package: pupmod-saz-timezone-6.1.0-1.el8.noarch from base
  unresolved deps:
    pupmod-puppetlabs-stdlib < 7.0.0
package: pupmod-simp-simp-4.16.3-1.el8.noarch from base
  unresolved deps:
    pupmod-puppet-chrony < 2.0.0
package: pupmod-simp-simp_gitlab-0.7.0-1.el8.noarch from base
  unresolved deps:
    pupmod-puppet-chrony < 2.0.0
package: pupmod-trlinkin-nsswitch-2.2.0-1.el8.noarch from base
  unresolved deps:
    pupmod-puppetlabs-stdlib < 7.0.0
```

For the most part, these are not difficult to fix. Unfortunately `systemd` had breaking changes at `3.X` which will require some larger code rework to resolve.

## Options

We have two courses of action:

1. Roll back the update to `stdlib` and update the other items (should be fine)
2. Make the necessary `systemd`-releated changes and push forward.

## Recommendation

Roll back and address the `systemd` module changes immediately after 6.6.0 is released.

**Comment by trevor-vaughan** [comment]
Pinged Saz on https://github.com/saz/puppet-timezone/issues/106 to see if the `timezone` module can get out without the `stdlib` dependency.

**Comment by trevor-vaughan** [comment]
The main branch of the Vox modules seem to have fixed things for `stdlib` but not all of them have been released.

**Comment by trevor-vaughan** [comment]
Submitted a [PR ](https://github.com/trlinkin/puppet-nsswitch/pull/44) to fix the issues with `nsswitch`. May need to fork if there is not a timely response.

**Comment by op-ct** [comment]
> The main branch of the Vox modules seem to have fixed things for `stdlib` but not all of them have been released.

This seems like the situation from before.  Debating between updating the simp- forks to the unreleased versions or try to  get voxpup to release the updates

**Comment by trevor-vaughan** [comment]
@op-ct The differences in the versions aren't huge (mostly just dropping support for dead OSs) so I think that releasing 6.6.0 with the earlier versions is the way to go.

**Comment by trevor-vaughan** [comment]
Related Updates to Vox modules:
* https://github.com/voxpupuli/puppet-augeasproviders/pull/173
* https://github.com/voxpupuli/puppet-augeasproviders_ssh/pull/72

Loosely related for tracking:
* https://github.com/voxpupuli/puppet-windows_firewall/pull/129
* https://github.com/voxpupuli/puppet-windowsfeature/pull/148

**Comment by trevor-vaughan** [comment]
Release PRs:
* https://github.com/voxpupuli/puppet-firewalld/pull/326
* https://github.com/voxpupuli/puppet-windows_firewall/pull/130
* https://github.com/voxpupuli/puppet-windowsfeature/pull/149
