### ISSUE TITLE
Push new puppet module RPMs

### ISSUE THREAD

**Issue by trevor-vaughan** [simp/simp-core#840]
We need to get the updated RPMs into the upstream repositories.

* [x] [simp/pupmod-voxpupuli-systemd](https://github.com/simp/pupmod-voxpupuli-systemd)
  * Tag: `v3.10.0`
* [x] [simp/pupmod-voxpupuli-firewalld](https://github.com/simp/pupmod-voxpupuli-firewalld)
  * Stuck: voxpupuli/puppet-firewalld#326
  * May need to bump our internal overrides for `v4.4.0`
* [x] [simp/pupmod-voxpupuli-kmod](https://github.com/simp/pupmod-voxpupuli-kmod)
  * Tag: `v3.2.0`
* [x] [simp/pupmod-voxpupuli-snmp](https://github.com/simp/pupmod-voxpupuli-snmp)
  * Tag: `v6.0.0`
* [x] [simp/pupmod-voxpupuli-yum](https://github.com/simp/pupmod-voxpupuli-yum)
  * Tag: `v5.6.1`
* [x] [simp/pupmod-puppetlabs-puppet_authorization](https://github.com/simp/pupmod-puppetlabs-puppet_authorization)
  * Stuck: puppetlabs/puppetlabs-puppet_authorization#37
  * Probably need to override deps locally for `0.5.1`
* [x] [simp/pupmod-puppetlabs-puppetdb](https://github.com/simp/pupmod-puppetlabs-puppetdb)
  * Tag: `7.10.0`
* [x] [simp/pupmod-saz-timezone](https://github.com/simp/pupmod-saz-timezone)
  * Tag: `v6.2.0`
* [x] [simp/pupmod-simp-simp](https://github.com/simp/pupmod-simp-simp)
  * The [CI Job](https://github.com/simp/pupmod-simp-simp/runs/6937037996?check_suite_focus=true) for this appears to have run and indicates that the artifact was uploaded however, the artifact does not appear to be on download.simp-project.com
* [x] [simp/pupmod-simp-simp_gitlab](https://github.com/simp/pupmod-simp-simp_gitlab)
  * Needs update and release
* [x] [simp/pupmod-trlinkin-nsswitch](https://github.com/simp/pupmod-trlinkin-nsswitch)
  * Tag: `simp-2.3.0`

```shell
package: pupmod-camptocamp-systemd-2.12.0-1.el8.noarch from base
  unresolved deps:
    pupmod-puppetlabs-stdlib < 7.0.0
package: pupmod-puppet-firewalld-4.4.0-1.el8.noarch from base
  unresolved deps:
    pupmod-puppetlabs-stdlib < 7.0.0
package: pupmod-puppet-kmod-3.0.0-1.el8.noarch from base
  unresolved deps:
    pupmod-puppetlabs-stdlib < 7.0.0
package: pupmod-puppet-snmp-5.1.1-1.el8.noarch from base
  unresolved deps:
    pupmod-puppetlabs-stdlib < 7.0.0
package: pupmod-puppet-yum-4.3.0-1.el8.noarch from base
  unresolved deps:
    pupmod-puppetlabs-stdlib < 7.0.0
    pupmod-puppetlabs-concat < 7.0.0
package: pupmod-puppetlabs-puppet_authorization-0.5.1-1.el8.noarch from base
  unresolved deps:
    pupmod-puppetlabs-stdlib < 7.0.0
    pupmod-puppetlabs-concat < 7.0.0
package: pupmod-puppetlabs-puppetdb-7.5.0-1.el8.noarch from base
  unresolved deps:
    pupmod-puppetlabs-postgresql < 7.0.0
    pupmod-puppetlabs-stdlib < 7.0.0
package: pupmod-saz-timezone-6.1.0-1.el8.noarch from base
  unresolved deps:
    pupmod-puppetlabs-stdlib < 7.0.0
package: pupmod-simp-simp-4.16.3-1.el8.noarch from base
  unresolved deps:
    pupmod-puppet-chrony < 2.0.0
package: pupmod-simp-simp_gitlab-0.7.0-1.el8.noarch from base
  unresolved deps:
    pupmod-puppet-chrony < 2.0.0
package: pupmod-trlinkin-nsswitch-2.2.0-1.el8.noarch from base
  unresolved deps:
    pupmod-puppetlabs-stdlib < 7.0.0
```

**Comment by trevor-vaughan** [comment]
@op-ct Tried to release `systemd` but got a [strange error](https://github.com/simp/pupmod-simp-aide/runs/7592658909?check_suite_focus=true).

**Comment by op-ct** [comment]
To improve upstream PR responses for [simp/pupmod-puppetlabs-puppet_authorization](https://github.com/simp/pupmod-puppetlabs-puppet_authorization), I'm adopting those to modules into voxpupuli:
  * https://github.com/voxpupuli/puppet-hocon/pull/1
  * https://github.com/voxpupuli/puppet-puppet_authorization/pull/1
