### ISSUE TITLE
The `GPGKEYS` directory is not being copied into `/var/www/yum/SIMP` on initial ISO install

### ISSUE THREAD

**Issue by trevor-vaughan** [simp/simp-core#859]

**Comment by trevor-vaughan** [comment]
It looks like this is going to have to go into the `bootstrap` of `simp-cli`.

The anaconda version in EL7 doesn't have `%pre-install` which is where the directory creation would have to go in order to make the `simp-gpgkeys` package work properly post-install.

**Comment by trevor-vaughan** [comment]
I believe that this is resolved with simp/simp-core#861

**Comment by AndyAdrian-OP** [comment]
closing as resolved with https://github.com/simp/simp-core/pull/861
